spring:
  profiles:
    active: dev
  datasource:
    testOnBorrow: true
    driver-class-name: ${MARKETBOM2_DATASOURCE_DRIVER}
    url: ${MARKETBOM2_DATASOURCE_URL}
    username: ${MARKETBOM2_DATASOURCE_USERNAME}
    password: ${MARKETBOM2_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: ${MARKETBOM2_MAX_POOL}
      minimum-idle: ${MARKETBOM2_MIN_IDLE}
      connection-timeout: 60000
      validation-timeout: 10000
      data-source-properties:
        rewriteBatchedStatements: true
      driverClassName: ${MARKETBOM2_DATASOURCE_DRIVER}
      jdbcUrl: ${MARKETBOM2_DATASOURCE_URL}
      username: ${MARKETBOM2_DATASOURCE_USERNAME}
      password: ${MARKETBOM2_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 500
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
        query:
          in_clause_parameter_padding: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${MARKETBORO_SES_KEY_ID}
      secretKey: ${MARKETBORO_SES_KEY_SECRET}
    apiGateway:
      baseUrl: ${MARKETBORO_API_GATEWAY}
      username: ${MARKETBORO_API_GATEWAY_USERNAME}
      password: ${MARKETBORO_API_GATEWAY_PASSWORD}
    provendor:
      content: ${MARKETBOM2_AWS_PROVENDOR_CONTENT_URL}
    bucket:
      public: ${MARKETBOM2_PUBLIC_BUCKET}
      private: ${MARKETBOM2_PRIVATE_BUCKET}
      common: # ?? ??
        private: ${COMMON_PRIVATE_BUCKET}

logging:
  config: ${MARKETBOM2_LOG_CONFIG_PATH:classpath:logback.xml}
  level:
    root: info
    jdbc:
      sqltiming: debug
      resultsettable: ${MARKETBOM2_LOG_JDBC_RESULT_SET:info} # DB resultSet 출력 [debug:출력, info이상: 미출력]
    org.springframework: info
    org.springframework.data.redis: error
    org.springframework.cloud.openfeign: info
    #    org.hibernate: debug # Hibernate Logging
    #    org.hibernate.engine.internal: info
    com:
      marketboro: debug
      zaxxer:
        hikari.HikariConfig: info
        hikari: info
  #    org.springframework.cache: trace # 서버가 기동될때, @Cache관련 어노테이션 메소드들이 등록되는지 확인가능.(AbstractFallbackCacheOperationSource)
